### ISSUE TITLE
Make the red background color expand the full width of the page

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-tako#2]
What happened.. 
![width](https://cloud.githubusercontent.com/assets/539962/8820519/1f74d240-300b-11e5-854d-4bb520222ac4.jpg)

due date: 
7-23-15 10p

**Comment by AaronAguilar** [comment]
Done and FTP'd! 
<img width="1381" alt="screen shot 2015-07-22 at 12 32 20 pm" src="https://cloud.githubusercontent.com/assets/10875354/8835192/c2cf72c6-306d-11e5-85f3-919bbf2297e7.png">

**Comment by rodneystrong** [comment]
Excellent job sir!!

I like how you relied on the built-in bootstrap classes to fix this issue rather than write extra code to override the styling. You're gettin good at this!
